# Generated by Django 3.2.5 on 2021-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votantes',
            options={'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
        migrations.AddField(
            model_name='votantes',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='votantes',
            name='estado_voto',
            field=models.BooleanField(default=False),
        ),
    ]
