# Generated by Django 3.2.5 on 2021-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votantes',
            options={'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
        migrations.AlterField(
            model_name='votantes',
            name='dependencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
