# Generated by Django 3.2.5 on 2021-07-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votantes',
            name='numero',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
