# Generated by Django 3.2.5 on 2021-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0003_alter_votantes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votantes',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='votantes',
            name='dependencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
