# Generated by Django 3.2.5 on 2021-07-22 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0004_auto_20210721_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votantes',
            name='cedula',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{5,15}$')], verbose_name='Numero de identificación'),
        ),
    ]
