# Generated by Django 3.2.2 on 2022-10-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0005_alter_votantes_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_candidate', models.CharField(max_length=30, verbose_name='Tipo de candidato')),
            ],
        ),
    ]
