# Generated by Django 3.2.2 on 2022-10-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0006_tipo_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='votantes',
            name='tipo_candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votante_tipo_candidato', to='votantes.tipo_candidato'),
            preserve_default=False,
        ),
    ]
