# Generated by Django 3.2.2 on 2022-10-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0007_votantes_tipo_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votantes',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='votantes',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='votantes',
            name='numero',
        ),
    ]
