# Generated by Django 3.2.2 on 2022-10-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0008_auto_20221013_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_candidato',
            options={'verbose_name': 'Tipo de Candidato', 'verbose_name_plural': 'Tipos de candidato'},
        ),
    ]
