# Generated by Django 3.2.2 on 2022-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0009_alter_tipo_candidato_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='votantes',
            name='num_tarjeton',
            field=models.IntegerField(default=1, verbose_name='Número del tarjetón'),
        ),
    ]
