# Generated by Django 3.2.2 on 2022-10-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0010_votantes_num_tarjeton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votantes',
            name='num_tarjeton',
        ),
    ]
