<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-12 13:07

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.5 on 2021-07-13 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
>>>>>>> 66d464de40f32ecdfa282a81e20637cf901941f5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
=======
                ('apellido', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('dependencia', models.CharField(max_length=100, null=True)),
>>>>>>> 66d464de40f32ecdfa282a81e20637cf901941f5
                ('foto', models.ImageField(upload_to='candidatos', verbose_name='Foto Candidato')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
>>>>>>> 66d464de40f32ecdfa282a81e20637cf901941f5
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votantes.votantes', unique=True)),
            ],
            options={
                'verbose_name': 'eleccion',
                'verbose_name_plural': 'elecciones',
                'unique_together': {('candidato', 'votante')},
            },
        ),
    ]
