# Generated by Django 3.2.5 on 2021-07-12 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0002_auto_20210712_1413'),
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dependencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
