# Generated by Django 3.2.5 on 2021-07-12 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0002_auto_20210712_1413'),
        ('candidatos', '0002_auto_20210712_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votantes.votantes', unique=True)),
            ],
            options={
                'verbose_name': 'eleccion',
                'verbose_name_plural': 'elecciones',
                'unique_together': {('candidato', 'votante')},
            },
        ),
    ]
