# Generated by Django 3.2.2 on 2022-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_eleccion_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='num_tarjeton',
            field=models.IntegerField(default=1, verbose_name='Número del tarjetón'),
        ),
    ]
